DragonMars/grace-shopper

client/components/navbar.js, package-lock.json, package.json
I changed the title of our project!
=> fix(navbar): updated title

package-lock.json, package.json, server/db/index.js, server/db/models/category.js, server/db/models/index.js, server/db/models/line-items.js, server/db/models/product.js
=> feat: Product, Category, LineItem models complete

package-lock.json, package.json, server/db/models/index.js, server/db/models/line-items.js, server/db/models/order.js, server/db/models/shippingAddress.js, server/db/models/user.js, server/test/model.spec.js
Added Order, User, ShippingAddress models with associations. Changed imports/exports. Added a test file for models.
=> Sequelize models

package.json, script/seed.js, server/api/users.js, server/db/index.js, server/db/models/order.js, server/test/model.spec.js, server/test/order.spec.js, server/test/shippingAddress.spec.js, server/test/user.spec.js, server/test/usersRoute.spec.js
Made tests for ShippingAddress model. All tests passing.
=> Sequelize test

server/api/index.js, server/api/products.js, server/db/models/index.js, server/test/productsRoute.spec.js
…&& test: corresponding tests added and passed
=> feat: api routes addedd to get all products and products by category

server/api/products.js, server/db/models/shippingAddress.js, server/test/productsRoute.spec.js, server/test/shippingAddress.spec.js
=> feat: single-product-API-route-and-test

client/components/order-confirmation.js, script/seed.js, server/api/orders.js, server/db/models/category.js, server/db/models/index.js, server/db/models/line-items.js, server/db/models/order.js, server/db/models/product.js, server/db/models/user.js, server/test/productsRoute.spec.js
=> Fix: Updated User and LineItem Association and Updated Seed File

client/components/index.js, client/components/order-confirmation.js, client/components/order-products.js, client/routes.js, server/db/models/user.js
User model with salts and passwords. 
Order items dummy components takes lineItems and an order, and calculates total based on whether an order is passed in or not
=> Order items component/ updated user model

client/store/order.js, server/api/category.js, server/api/orders.js
=> Updated order route

client/components/all-product-container.js, client/components/all-product-single-view.js, client/components/auth-form.js, client/components/checkout.js, client/components/navbar.js, client/components/order-confirmation.js, client/components/shipping-address-form.js, client/components/single-product.js, package-lock.json, package.json, public/index.html
=> fix/updated react components with semantic-ui-react

client/components/single-product.js, client/store/line-items.js
=> fixed functionality for guest and logged in add to cart

client/components/checkout.js, client/components/order-products.js, client/store/order.js, server/api/orders.js
=> Fix: Order to Checkout Process complete

client/components/checkout.js, client/components/shipping-address-form.js, client/components/stripe-components/CheckoutForm.js, client/components/stripe-components/StripeContainer.js, server/db/models/index.js
=> Fix: updated checkout view

client/components/categorybar.js, client/store/category.js, server/api/users.js, server/test/usersRoute.spec.js
=> feat: category bar and added isAdmin privilege to api user route

client/components/single-product.js, client/store/line-items.js
=> fix: can add any item to cart

client/components/checkout.js, client/components/index.js, client/components/order-confirmation.js, client/components/order-products.js, client/components/user-home.js, script/seed.js, server/api/orders.js
=> Feat: order history shows up for individual users

client/components/order-confirmation.js, client/components/user-home.js, server/api/orders.js
=> feat: cart cleared before order confirmation unmounts

client/components/all-product-container.js, client/components/all-product-single-view.js, client/components/cart.js, client/components/category-bar.js, client/components/checkout.js, client/components/navbar.js, client/components/order-products.js, client/components/single-product.js, client/components/stripe-components/checkout-form.js, public/index.html, public/style.css
=> feat: styling for home page, cart

client/components/category-bar.js, client/components/single-product.js, client/routes.js
=> side bar added

client/components/order-confirmation.js
=> update: order confirmation UI

client/components/user-home.js, client/components/user-home.spec.js
=> Feat: order history styling

.travis.yml
=> change heroku app name
